name: camera
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.10.6

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation
      web:
        default_package: camera_web

dependencies:
  camera_android:
    git:
      url: https://github.com/q1593315291/camera.git  #必填，仓库地址
      ref: badb8b75414fad287846b759c777fc025e6d7a7e
      path: packages/camera/camera_android #代码相对路径，当代码不在仓库根目录时需要填
  camera_avfoundation: ^0.9.9
  camera_platform_interface: ^2.3.2
  camera_web: ^0.3.1
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2
  quiver: ^3.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: 5.3.2
  plugin_platform_interface: ^2.0.0
  video_player: ^2.0.0
